package tankblaster

var englishStrings = localizedStrings{
	PlayerSelectionTitle:                 "TANK BLASTER",
	PlayerSelectionRounds:                "Rounds",
	PlayerSelectionSlotNone:              "None",
	PlayerSelectionSlotHuman:             "Human",
	PlayerSelectionSlotComputer:          "Computer",
	PlayerSelectionHelpHint:              "Press F1 for help",
	PlayerSelectionOptionsButton:         "Options",
	PlayerSelectionStartButton:           "Start >>",
	PlayerSelectionMinimumPlayers:        "Select at least two players",
	PlayerSelectionHelpTitle:             "Tank Blaster Help",
	PlayerSelectionHelpSlotNone:          "None",
	PlayerSelectionHelpHuman:             "Human",
	PlayerSelectionHelpPlayerName:        "Player 1",
	PlayerSelectionHelpPlayerType:        "Change player type",
	PlayerSelectionHelpColor:             "Change color",
	PlayerSelectionHelpName:              "Change name",
	PlayerSelectionHelpComputerType:      "Change computer type",
	PlayerSelectionHelpKeys:              "Keys",
	PlayerSelectionHelpKeyIncreaseRounds: "+      Increase rounds",
	PlayerSelectionHelpKeyDecreaseRounds: "-      Decrease rounds",
	PlayerSelectionHelpKeyOptions:        "O      Open options",
	PlayerSelectionHelpKeyStart:          "ESC    Start game",
	OptionsTitle:                         "Tank Blaster Options",
	OptionsProjectileReentry:             "Projectile Reentry",
	OptionsProjectileReentryOff:          "off",
	OptionsProjectileReentryAlways:       "always on",
	OptionsProjectileReentryRandom:       "random",
	OptionsCloudAggression:               "Cloud Aggression",
	OptionsPalmCount:                     "Number of Trees",
	OptionsRoundStart:                    "Round Start",
	OptionsQuickRoundStart:               "quick round start",
	OptionsLanguageButton:                "Language...",
	LanguageTitle:                        "Select Language",
	LanguageGerman:                       "deutsch",
	LanguageEnglish:                      "english",
	GameDefaultPlayerName:                "Player",
	GameHUDStrength:                      "Strength",
	GameHUDAngle:                         "Angle",
	GameHUDFire:                          "Fire!",
	GameHUDIgnition:                      "Ignition",
	GameHUDWind:                          "Wind",
	GameHUDPower:                         "Power",
	GameScoreRound:                       "Round",
	GameScoreOf:                          "of",
	GameScorePlayer:                      "Player",
	GameScoreSuccess:                     "Score",
	GameScoreStatus:                      "Status",
	GameStatusActive:                     "active",
	GameStatusOut:                        "out",
	GameStatusEliminated:                 "eliminated",
	GamePause:                            "Pause",
	GameHelpTitle:                        "Tank Blaster Help",
	GameHelpKeys:                         "Keys",
	GameHelpFire:                         "Fire!",
	GameHelpNextWeapon:                   "Select next (previous) weapon",
	GameHelpRotateClockwise:              "Rotate angle by 1° (10°) clockwise",
	GameHelpRotateCounterClockwise:       "Rotate angle by 1° (10°) counterclockwise",
	GameHelpIncreaseStrength:             "Increase strength by 1 (10)",
	GameHelpDecreaseStrength:             "Decrease strength by 1 (10)",
	GameHelpIgnition:                     "Start engine (XM-V12 tank only)",
	GameHelpInvertAngle:                  "Invert angle",
	GameHelpScrollOMat:                   "Toggle Scroll-o-Mat (scroll with arrow keys)",
	GameHelpIncreaseStrengthByTen:        "Increase strength by 10",
	GameHelpDecreaseStrengthByTen:        "Decrease strength by 10",
	GameHelpPlayerInfo:                   "Info about player 1, 2, ..., 10",
	GameHelpScoreTable:                   "Show score table",
	GameHelpQuit:                         "Quit game (back to Windows)",
	GameHelpAbortRound:                   "Abort current round",
	GameHelpPause:                        "Pause",
	GameHelpTogglePlayerNames:            "Toggle player names",
	PlayerInfoTitle:                      "Player Information",
	PlayerInfoMissing:                    "Player not available",
	PlayerInfoTankModel:                  "Tank model",
	PlayerInfoStandardTank:               "Standard",
	PlayerInfoStatus:                     "Status:",
	PlayerInfoEnergy:                     "Energy:",
	PlayerInfoMoney:                      "Money:",
	PlayerInfoEnergyShield:               "Energy shield",
	PlayerInfoArsenal:                    "Weapon arsenal",
	PlayerInfoTrainingAmmo:               "Tracer round",
	RoundTransitionPlayed:                "played,",
	RoundTransitionRemainingRounds:       "rounds remaining.",
	XMV12MotorOff:                        "Engine off",
	ShopClassA:                           "- Class A -",
	ShopClassB:                           "- Bargains -",
	ShopContinue:                         "Continue",
	ShopBack:                             "Back >>",
	ShopQuantity:                         "Quantity",
	ShopPrice:                            "Price",
	ShopBuy:                              "Buy",
	ShopBargainBuy:                       "Deal!",
	ShopMoney:                            "Money",
	ShopStock:                            "Stock",
	ItemTrainingAmmo:                     "Tracer Round",
	ItemGrenade:                          "Grenade",
	ItemLargeGrenade:                     "Large Grenade",
	ItemAtomBomb:                         "Atom Bomb",
	ItemHBomb:                            "H-Bomb",
	ItemPlasmaMelter:                     "Plasma Melter",
	ItemWonderPalm:                       "Wonder Palm",
	ItemFireball:                         "Fireball",
	ItemWater:                            "Water",
	ItemMoles:                            "Moles",
	ItemMFSTriple:                        "MFS Triple",
	ItemSmallCrumblers:                   "Small Crumbler",
	ItemLargeCrumblers:                   "Large Crumbler",
	ItemSurpriseEgg:                      "Surprise Egg",
	ItemMosquitos:                        "Mosquitos",
	ItemShockwave:                        "Shockwave",
	ItemAirStrike:                        "Air Strike",
	ItemSplitterBomb:                     "Splitter Bomb",
	ItemLaser:                            "Laser",
	ItemScrollOMat:                       "Scroll-o-Mat",
	ItemEnergyShield:                     "Energy Shield",
	ItemMFSBooster:                       "MFS Booster",
	ItemXMV12Tank:                        "XM-V12 Tank",
	ItemDiesel:                           "Diesel (F54)",
	DialogOK:                             "OK",
	DialogCancel:                         "Cancel",
}
