package tankblaster

var germanStrings = localizedStrings{
	PlayerSelectionTitle:                 "TANK BLASTER",
	PlayerSelectionRounds:                "Anzahl Runden",
	PlayerSelectionSlotNone:              "Keiner",
	PlayerSelectionSlotHuman:             "Mensch",
	PlayerSelectionSlotComputer:          "Computer",
	PlayerSelectionHelpHint:              "Druecken Sie F1 fuer Hilfe",
	PlayerSelectionOptionsButton:         "Optionen",
	PlayerSelectionOnlineButton:          "Onlinespiel",
	PlayerSelectionStartButton:           "Start >>",
	PlayerSelectionMinimumPlayers:        "Mindestens zwei Spieler auswaehlen",
	PlayerSelectionHelpTitle:             "Tank Blaster Hilfe",
	PlayerSelectionHelpSlotNone:          "None",
	PlayerSelectionHelpHuman:             "Human",
	PlayerSelectionHelpPlayerName:        "Player 1",
	PlayerSelectionHelpPlayerType:        "Spielertyp ändern",
	PlayerSelectionHelpColor:             "Farbe ändern",
	PlayerSelectionHelpName:              "Name ändern",
	PlayerSelectionHelpComputerType:      "Computertyp ändern",
	PlayerSelectionHelpKeys:              "Tasten",
	PlayerSelectionHelpKeyIncreaseRounds: "+      Rundenzahl erhöhen",
	PlayerSelectionHelpKeyDecreaseRounds: "-      Rundenzahl verringern",
	PlayerSelectionHelpKeyOptions:        "O      Optionen einstellen",
	PlayerSelectionHelpKeyStart:          "ESC    Spiel starten",
	OptionsTitle:                         "Tank Blaster Optionen",
	OptionsProjectileReentry:             "Geschoss Wiedereintritt",
	OptionsProjectileReentryOff:          "aus",
	OptionsProjectileReentryAlways:       "immer an",
	OptionsProjectileReentryRandom:       "Zufall",
	OptionsCloudAggression:               "Aggressivität der Wolke",
	OptionsPalmCount:                     "Anzahl Bäume",
	OptionsRoundStart:                    "Rundenstart",
	OptionsQuickRoundStart:               "schneller Rundenstart",
	OptionsLanguageButton:                "Sprache...",
	LanguageTitle:                        "Sprache auswählen",
	LanguageGerman:                       "deutsch",
	LanguageEnglish:                      "english",
	OnlineTitle:                          "Online-Multiplayer",
	OnlineDisplayName:                    "Spielername",
	OnlineQuickMatch:                     "Schnelles Spiel",
	OnlineCreatePublicSession:            "Öffentliche Session erstellen",
	OnlineCreatePrivateSession:           "Private Session erstellen",
	OnlineOpenSessions:                   "Offene Sessions",
	OnlineJoinSession:                    "Session beitreten",
	OnlineLeaderboard:                    "Bestenliste",
	OnlineReady:                          "Bereit",
	OnlineLeave:                          "Verlassen",
	OnlineBack:                           "Zurueck",
	OnlineJoinPrompt:                     "Join-Code oder Einladungslink",
	OnlineConnecting:                     "Verbinde...",
	OnlineConnected:                      "Verbunden",
	OnlineQueued:                         "Warte auf Gegner...",
	OnlineSessionCreated:                 "Session erstellt",
	OnlineSessionJoined:                  "Session beigetreten",
	OnlineInviteLink:                     "Einladungslink",
	OnlineCopiedCode:                     "Join-Code kopiert",
	OnlineCopiedInviteLink:               "Einladungslink kopiert",
	OnlineClipboardUnavailable:           "Zwischenablage nicht verfügbar",
	OnlineNoSessions:                     "Keine offenen Sessions",
	OnlineNoLeaderboard:                  "Keine Bestenlisteneinträge",
	OnlineMatchStarted:                   "Match gestartet",
	GameDefaultPlayerName:                "Spieler",
	GameHUDStrength:                      "Stärke",
	GameHUDAngle:                         "Winkel",
	GameHUDFire:                          "Feuer!",
	GameHUDIgnition:                      "Anlasser",
	GameHUDWind:                          "Wind",
	GameHUDPower:                         "Power",
	GameScoreRound:                       "Runde",
	GameScoreOf:                          "von",
	GameScorePlayer:                      "Spieler",
	GameScoreSuccess:                     "Erfolg",
	GameScoreStatus:                      "Status",
	GameStatusActive:                     "aktiv",
	GameStatusOut:                        "aus",
	GameStatusEliminated:                 "ausgeschieden",
	GamePause:                            "Pause",
	GameHelpTitle:                        "Tank Blaster Hilfe",
	GameHelpKeys:                         "Tasten",
	GameHelpFire:                         "Feuer!",
	GameHelpNextWeapon:                   "Nächste (vorige) Waffe wählen",
	GameHelpRotateClockwise:              "Winkel um 1° (10°) im UZS drehen",
	GameHelpRotateCounterClockwise:       "Winkel um 1° (10°) gegen UZS drehen",
	GameHelpIncreaseStrength:             "Kraft um 1 (10) erhöhen",
	GameHelpDecreaseStrength:             "Kraft um 1 (10) verringern",
	GameHelpIgnition:                     "Motor anlassen (nur XM-V12 Panzer)",
	GameHelpInvertAngle:                  "Winkel invertieren",
	GameHelpScrollOMat:                   "Scroll-o-Mat ein-/ausschalten (mit Pfeiltasten scrollen)",
	GameHelpIncreaseStrengthByTen:        "Kraft um 10 erhöhen",
	GameHelpDecreaseStrengthByTen:        "Kraft um 10 verringern",
	GameHelpPlayerInfo:                   "Info über Spieler 1, 2, ..., 10",
	GameHelpScoreTable:                   "Punkte-Zwischenstand anzeigen",
	GameHelpQuit:                         "Spiel beenden (zurück zu Windows)",
	GameHelpAbortRound:                   "Laufende Runde abbrechen",
	GameHelpPause:                        "Pause",
	GameHelpTogglePlayerNames:            "Spielernamen ein-/ausblenden",
	PlayerInfoTitle:                      "Spieler-Information",
	PlayerInfoMissing:                    "Spieler nicht vorhanden",
	PlayerInfoTankModel:                  "Panzermodell",
	PlayerInfoStandardTank:               "Standard",
	PlayerInfoStatus:                     "Status:",
	PlayerInfoEnergy:                     "Energie:",
	PlayerInfoMoney:                      "Geld:",
	PlayerInfoEnergyShield:               "Energieschild",
	PlayerInfoArsenal:                    "Waffenarsenal",
	PlayerInfoTrainingAmmo:               "Spurgeschoß",
	RoundTransitionPlayed:                "gespielt, noch",
	RoundTransitionRemainingRounds:       "Runden.",
	XMV12MotorOff:                        "Motor aus",
	ShopClassA:                           "- Klasse A -",
	ShopClassB:                           "- Schnäppchen -",
	ShopContinue:                         "Weiter",
	ShopBack:                             "Zurueck >>",
	ShopQuantity:                         "Anzahl",
	ShopPrice:                            "Preis",
	ShopBuy:                              "Kaufen",
	ShopBargainBuy:                       "Zuschlagen!",
	ShopMoney:                            "Geld",
	ShopStock:                            "Vorrat",
	ItemTrainingAmmo:                     "Spurgeschoß",
	ItemGrenade:                          "Granate",
	ItemLargeGrenade:                     "Große Granate",
	ItemAtomBomb:                         "Atombombe",
	ItemHBomb:                            "H-Bombe",
	ItemPlasmaMelter:                     "Plasmaschmelzer",
	ItemWonderPalm:                       "Wunderpalme",
	ItemFireball:                         "Feuerkugel",
	ItemWater:                            "Wasser",
	ItemMoles:                            "Maulwürfe",
	ItemMFSTriple:                        "MFS 3-fach",
	ItemSmallCrumblers:                   "Brösler, klein",
	ItemLargeCrumblers:                   "Brösler, groß",
	ItemSurpriseEgg:                      "Überraschungsei",
	ItemMosquitos:                        "Moskitos",
	ItemShockwave:                        "Schockwelle",
	ItemAirStrike:                        "Luftschlag",
	ItemSplitterBomb:                     "Splitterbombe",
	ItemLaser:                            "Laser",
	ItemScrollOMat:                       "Scroll-o-Mat",
	ItemEnergyShield:                     "Energieschild",
	ItemMFSBooster:                       "MFS Verstärker",
	ItemXMV12Tank:                        "XM-V12 Panzer",
	ItemDiesel:                           "Diesel (F54)",
	DialogOK:                             "OK",
	DialogCancel:                         "Abbrechen",
}
